image: node

variables:
  PUBLIC_URL: http://root.pages.pogr.cc/google-docs-clone/

build:
  stage: build
  cache:
    paths:
      - client/node_modules/
  script:
    - cd client/
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  dependencies: 
    - build
  script:
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
